#!/usr/bin/env python3

import re
import subprocess
import sys

from src.commands.api import APICommand, APIAddCommand, APIDeleteCommand, APIListCommand
from src.commands.export import ExportCommand
from src.commands.help import HelpCommand
from src.commands.history import HistoryCommand
from src.commands.imp import ImportCommand
from src.commands.reset import ResetCommand
from src.commands.use import UseCommand
import src.data as data
from src.data import models
from src.data.queries import curl as cq


def format_bash(args):
    result = []
    for arg in args:
        res = arg
        if ' ' in arg:
            res = f"'{arg}'"
        result.append(res)
    return result


def run_command(command, args):
    COMMANDS = {
        'add': APIAddCommand,
        'api': APICommand,
        'delete': APIDeleteCommand,
        'export': ExportCommand,
        'help': HelpCommand,
        'history': HistoryCommand,
        'import': ImportCommand,
        'list': APIListCommand,
        'reset': ResetCommand,
        'use': UseCommand,
    }
    if command in COMMANDS.keys():
        return COMMANDS[command].run(args)
    if re.match(data.ID_REGEX, command):
        curl = cq.get_by_id(command)
        if not curl:
            raise Exception(f"Curl not found: '{command}'.")
        print(curl.command)
        pieces = curl.command.split(' ')
        shcmd = ' '.join(['curl', *format_bash(pieces[1:])])
        subprocess.call(shcmd, shell=True)
    else:
        shcmd = ' '.join(['curl', *format_bash(args[1:])])
        subprocess.call(shcmd, shell=True)
        cq.save_history(' '.join(['curls', *args[1:]]))


command = sys.argv[1] if len(sys.argv) > 1 else None
args = sys.argv[1:] if len(sys.argv) > 2 else []
models.init()
if not command:
    command = 'list'
try:
    run_command(command, sys.argv)
except Exception as e:
    print(e)
